package pdo

// PDO 属性常量
const (
	PDO_ATTR_AUTOCOMMIT          = 0
	PDO_ATTR_PREFETCH            = 1
	PDO_ATTR_TIMEOUT             = 2
	PDO_ATTR_ERRMODE             = 3
	PDO_ATTR_SERVER_VERSION      = 4
	PDO_ATTR_CLIENT_VERSION      = 5
	PDO_ATTR_SERVER_INFO         = 6
	PDO_ATTR_CONNECTION_STATUS   = 7
	PDO_ATTR_CASE                = 8
	PDO_ATTR_CURSOR_NAME         = 9
	PDO_ATTR_CURSOR              = 10
	PDO_ATTR_ORACLE_NULLS        = 11
	PDO_ATTR_PERSISTENT          = 12
	PDO_ATTR_STATEMENT_CLASS     = 13
	PDO_ATTR_FETCH_CATALOG_NAMES = 15
	PDO_ATTR_FETCH_TABLE_NAMES   = 16
	PDO_ATTR_STRINGIFY_FETCHES   = 17
	PDO_ATTR_MAX_COLUMN_LEN      = 18
	PDO_ATTR_DEFAULT_FETCH_MODE  = 19
	PDO_ATTR_EMULATE_PREPARES    = 20
	PDO_ATTR_DEFAULT_STR_PARAM   = 21
	PDO_ATTR_DRIVER_NAME         = 16

	// 错误模式
	PDO_ERRMODE_SILENT    = 0
	PDO_ERRMODE_WARNING   = 1
	PDO_ERRMODE_EXCEPTION = 2

	// CASE 常量
	PDO_CASE_NATURAL = 0
	PDO_CASE_UPPER   = 1
	PDO_CASE_LOWER   = 2

	// NULL 常量
	PDO_NULL_NATURAL      = 0
	PDO_NULL_EMPTY_STRING = 1
	PDO_NULL_TO_STRING    = 2

	// Fetch 模式
	PDO_FETCH_DEFAULT    = 0
	PDO_FETCH_LAZY       = 1
	PDO_FETCH_ASSOC      = 2
	PDO_FETCH_NUM        = 3
	PDO_FETCH_BOTH       = 4
	PDO_FETCH_OBJ        = 5
	PDO_FETCH_BOUND      = 6
	PDO_FETCH_COLUMN     = 7
	PDO_FETCH_CLASS      = 8
	PDO_FETCH_INTO       = 9
	PDO_FETCH_FUNC       = 10
	PDO_FETCH_GROUP      = 65536
	PDO_FETCH_UNIQUE     = 196608
	PDO_FETCH_KEY_PAIR   = 12
	PDO_FETCH_CLASSTYPE  = 262144
	PDO_FETCH_SERIALIZE  = 524288
	PDO_FETCH_PROPS_LATE = 1048576
	PDO_FETCH_NAMED      = 11

	// 参数类型
	PDO_PARAM_BOOL         = 5
	PDO_PARAM_NULL         = 0
	PDO_PARAM_INT          = 1
	PDO_PARAM_STR          = 2
	PDO_PARAM_LOB          = 3
	PDO_PARAM_STMT         = 4
	PDO_PARAM_INPUT_OUTPUT = 2147483648

	// Cursor 类型
	PDO_CURSOR_FWDONLY = 0
	PDO_CURSOR_SCROLL  = 1

	// MySQL 驱动专属属性常量（PDO::MYSQL_ATTR_*）
	PDO_MYSQL_ATTR_USE_BUFFERED_QUERY     = 1000
	PDO_MYSQL_ATTR_LOCAL_INFILE           = 1001
	PDO_MYSQL_ATTR_INIT_COMMAND           = 1002
	PDO_MYSQL_ATTR_COMPRESS               = 1003
	PDO_MYSQL_ATTR_DIRECT_QUERY           = 1004
	PDO_MYSQL_ATTR_FOUND_ROWS             = 1005
	PDO_MYSQL_ATTR_IGNORE_SPACE           = 1006
	PDO_MYSQL_ATTR_MAX_BUFFER_SIZE        = 1007
	PDO_MYSQL_ATTR_READ_DEFAULT_FILE      = 1008
	PDO_MYSQL_ATTR_READ_DEFAULT_GROUP     = 1009
	PDO_MYSQL_ATTR_CONNECT_TIMEOUT        = 1010
	PDO_MYSQL_ATTR_SERVER_PUBLIC_KEY      = 1011
	PDO_MYSQL_ATTR_MULTI_STATEMENTS       = 1012
	PDO_MYSQL_ATTR_SSL_CA                 = 1013
	PDO_MYSQL_ATTR_SSL_CAPATH             = 1014
	PDO_MYSQL_ATTR_SSL_CERT               = 1015
	PDO_MYSQL_ATTR_SSL_KEY                = 1016
	PDO_MYSQL_ATTR_SSL_CIPHER             = 1017
	PDO_MYSQL_ATTR_SSL_VERIFY_SERVER_CERT = 1018
)
